// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSuqtpgYPMC2fYUKmESdAR_Cgk29LGg2s',
    appId: '1:568083482056:web:50606150e039a2fd776cfd',
    messagingSenderId: '568083482056',
    projectId: 'vemp-quadra',
    authDomain: 'vemp-quadra.firebaseapp.com',
    storageBucket: 'vemp-quadra.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgPVi-AiLalLD1MusfSlV16qy3fsKdSxI',
    appId: '1:568083482056:android:cccd0d92a3a182de776cfd',
    messagingSenderId: '568083482056',
    projectId: 'vemp-quadra',
    storageBucket: 'vemp-quadra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtpfRxkUzrFnNimoapyWSQ3R4sZ3PphFU',
    appId: '1:568083482056:ios:6f82d124c6fcd5c9776cfd',
    messagingSenderId: '568083482056',
    projectId: 'vemp-quadra',
    storageBucket: 'vemp-quadra.appspot.com',
    iosClientId: '568083482056-da2afhd8hot72qdpumn2f5a0fm5hnkdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.vempraquadra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtpfRxkUzrFnNimoapyWSQ3R4sZ3PphFU',
    appId: '1:568083482056:ios:6f82d124c6fcd5c9776cfd',
    messagingSenderId: '568083482056',
    projectId: 'vemp-quadra',
    storageBucket: 'vemp-quadra.appspot.com',
    iosClientId: '568083482056-da2afhd8hot72qdpumn2f5a0fm5hnkdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.vempraquadra',
  );
}
